#!/bin/bash
# Regenerates the measured cells of docs/COMPATIBILITY.md from soak data. Everything between
# the two "generated" markers is replaced by the output of `jilpa-soak matrix`; the rest of the
# document is written by hand. No cell is advertised without counts, so a cell with no data
# file has no row.
#
# usage: Scripts/make-compatibility.sh [data-dir]      default: Tools/spikes/data/s2
#
# Only files named main-*, cover-* and target-* are plain navigation cells. Fault, race and
# strategy-comparison files are experiments and stay out of the matrix.

set -euo pipefail
cd "$(dirname "$0")/.."

DATA="${1:-Tools/spikes/data/s2}"
DOC=docs/COMPATIBILITY.md
BEGIN='<!-- generated by Scripts/make-compatibility.sh: begin -->'
END='<!-- generated by Scripts/make-compatibility.sh: end -->'

FILES=()
while IFS= read -r file; do FILES+=("$file"); done < <(
  find "$DATA" -maxdepth 1 -type f \
    \( -name 'main-*.jsonl' -o -name 'cover-*.jsonl' -o -name 'target-*.jsonl' \) | sort)
if [ "${#FILES[@]}" -eq 0 ]; then
  echo "make-compatibility: no main-, cover- or target- data files in $DATA" >&2
  exit 1
fi
grep -qF "$BEGIN" "$DOC" && grep -qF "$END" "$DOC" || {
  echo "make-compatibility: $DOC has lost its generated markers" >&2
  exit 1
}

swift build --product jilpa-soak >/dev/null
TABLE="$(mktemp)"
trap 'rm -f "$TABLE" "$TABLE.doc"' EXIT
"$(swift build --show-bin-path)/jilpa-soak" matrix "${FILES[@]}" > "$TABLE"

awk -v begin="$BEGIN" -v end="$END" -v table="$TABLE" '
  $0 == begin { print; print ""; while ((getline line < table) > 0) print line; print ""; skip = 1; next }
  $0 == end { skip = 0 }
  !skip { print }
' "$DOC" > "$TABLE.doc"
mv "$TABLE.doc" "$DOC"
echo "make-compatibility: ${#FILES[@]} data files, $(($(wc -l < "$TABLE") - 2)) cells"
